name: Build Extension

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 1.0.1)'
        required: true
        default: '1.0.0'
      create_release:
        description: 'Create GitHub Release'
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Update version in package.json
        if: github.event_name == 'workflow_dispatch'
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          cd webview && npm version ${{ github.event.inputs.version }} --no-git-tag-version
          
      - name: Install dependencies
        run: |
          npm install
          cd webview && npm install
          
      - name: Build extension
        run: npm run compile
        
      - name: Package extension
        run: |
          npm install -g @vscode/vsce
          vsce package
          
      - name: Upload VSIX as artifact
        uses: actions/upload-artifact@v3
        with:
          name: extension-vsix-${{ github.event.inputs.version || github.ref_name }}
          path: '*.vsix'
          
      - name: Create Release
        if: github.event.inputs.create_release == 'true' || startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version && format('v{0}', github.event.inputs.version) || github.ref_name }}
          name: ${{ github.event.inputs.version && format('v{0} - Claude Code Logs Viewer', github.event.inputs.version) || github.ref_name }}
          files: '*.vsix'
          body: |
            ## Claude Code Logs Viewer ${{ github.event.inputs.version || github.ref_name }}

            Claude Code の会話ログを VS Code 内で見やすく表示する拡張機能です。

            ### 機能
            - **会話ログ表示**: `~/.claude/projects` 内に保存された Claude Code のログを表示
            - **セッション再開**: ログ詳細画面からボタン一つでターミナルでセッション再開

            ### インストール方法
            1. 下記の `.vsix` ファイルをダウンロード
            2. VS Code でコマンドパレット（`Ctrl+Shift+P` / `Cmd+Shift+P`）を開く
            3. `Extensions: Install from VSIX...` を選択
            4. ダウンロードした `.vsix` ファイルを選択
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}